"""add more scores to ai score

Revision ID: 41b55c3987b1
Revises: eb5a0e2d643d
Create Date: 2025-10-02 23:10:14.466156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b55c3987b1'
down_revision: Union[str, Sequence[str], None] = 'eb5a0e2d643d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_scores', sa.Column('ai_proportion', sa.Text(), nullable=True))
    op.add_column('ai_scores', sa.Column('business_role', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_scores', 'business_role')
    op.drop_column('ai_scores', 'ai_proportion')
    # ### end Alembic commands ###
