"""create chunk sumary and filing summary tables

Revision ID: eb5a0e2d643d
Revises: f9d8f3d5f744
Create Date: 2025-10-01 14:59:42.718008

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb5a0e2d643d"
down_revision: Union[str, Sequence[str], None] = "f9d8f3d5f744"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filing_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ai_score_id", sa.Integer(), nullable=True),
        sa.Column("cik", sa.String(), nullable=True),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("filing_type", sa.String(), nullable=True),
        sa.Column("accession_number", sa.String(), nullable=True),
        sa.Column("filing_date", sa.String(), nullable=True),
        sa.Column("raw_text_length", sa.Integer(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["ai_score_id"], ["ai_scores.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_filing_summaries_accession_number"),
        "filing_summaries",
        ["accession_number"],
        unique=True,
    )
    op.create_index(
        op.f("ix_filing_summaries_ai_score_id"),
        "filing_summaries",
        ["ai_score_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_filing_summaries_cik"), "filing_summaries", ["cik"], unique=False
    )
    op.create_index(
        op.f("ix_filing_summaries_id"), "filing_summaries", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_filing_summaries_ticker"), "filing_summaries", ["ticker"], unique=False
    )
    op.create_table(
        "chunk_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filing_summary_id", sa.Integer(), nullable=True),
        sa.Column("ai_score_id", sa.Integer(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_text_length", sa.Integer(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["ai_score_id"], ["ai_scores.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["filing_summary_id"], ["filing_summaries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chunk_summaries_ai_score_id"),
        "chunk_summaries",
        ["ai_score_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chunk_summaries_filing_summary_id"),
        "chunk_summaries",
        ["filing_summary_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chunk_summaries_id"), "chunk_summaries", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chunk_summaries_id"), table_name="chunk_summaries")
    op.drop_index(
        op.f("ix_chunk_summaries_filing_summary_id"), table_name="chunk_summaries"
    )
    op.drop_index(op.f("ix_chunk_summaries_ai_score_id"), table_name="chunk_summaries")
    op.drop_table("chunk_summaries")
    op.drop_index(op.f("ix_filing_summaries_ticker"), table_name="filing_summaries")
    op.drop_index(op.f("ix_filing_summaries_id"), table_name="filing_summaries")
    op.drop_index(op.f("ix_filing_summaries_cik"), table_name="filing_summaries")
    op.drop_index(
        op.f("ix_filing_summaries_ai_score_id"), table_name="filing_summaries"
    )
    op.drop_index(
        op.f("ix_filing_summaries_accession_number"), table_name="filing_summaries"
    )
    op.drop_table("filing_summaries")
    # ### end Alembic commands ###
